spring.application.name=EmpTrack

#
# JDBC properties
#
#spring.datasource.url=jdbc:mysql://localhost:3306/employee_directory
spring.datasource.url=jdbc:mysql://localhost:3306/emptrack
spring.datasource.username=emptrack
spring.datasource.password=Sonu@1234

spring.security.user.name=sonu
spring.security.user.password=sonu1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
